### ISSUE TITLE
No longer functioning in Big Sur

### ISSUE THREAD

**Issue by jetpants** [rodrigobdz/alfred-swap-user-workflow#2] opened 2021-11-08 16:15 UTC
Great utility - just what I was looking for :)

Some things appear to have moved around with Big Sur. The "User.menu" part of the path on the last line does not exist any more.

Any idea where this is located now?

Many thanks,
Steve

**Comment by rodrigobdz** [comment] 2021-11-09 18:07
Hi, @jetpants! I'm glad to hear you're liking it. 

Unfortunately, Apple has deleted this script and there seems to be no replacement for it, see  https://github.com/rodrigobdz/alfred-swap-user-workflow/issues/1#issuecomment-956791305. I'll close this issue as duplicate of https://github.com/rodrigobdz/alfred-swap-user-workflow/issues/1. 
I'll keep an eye out for a fix in the future.

**Closed as completed by rodrigobdz** 2021-11-09 18:07 UTC
Labels: duplicate

**Comment by jetpants** [comment] 2021-11-09 18:36
Thanks for replying anyway! :)
